apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-29T20:35:20.404230
    description: This image contains the Kabanero development stack for the Nodejs
      Loopback collection
    distribution-scope: public
    help: For more information visit https://github.com/sclorg/s2i-nodejs-container
    image.opencontainers.org/created: "2020-02-06T11:17:26-05:00"
    k8s.io/description: Node.js 10 available as container is a base platform for building
      and running various Node.js 10 applications and frameworks. Node.js is a platform
      built on Chrome's JavaScript runtime for easily building fast, scalable network
      applications. Node.js uses an event-driven, non-blocking I/O model that makes
      it lightweight and efficient, perfect for data-intensive real-time applications
      that run across distributed devices.
    k8s.io/display-name: Node.js 10
    maintainer: SoftwareCollections.org <sclorg@redhat.com>
    name: kabanero/nodejs-loopback
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,nodejs,nodejs10
    redhat.com/build-host: cpt-1006.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: nodejs-10-container
    redhat.com/deployments-dir: /opt/app-root/src
    redhat.com/dev-mode: DEV_MODE:false
    redhat.com/dev-mode.port: DEBUG_PORT:5858
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "54"
    s2i.io/scripts-url: image:///usr/libexec/s2i
    s2i.openshift.io/scripts-url: image:///usr/libexec/s2i
    stack.appsody.dev/authors: Raymond Feng <enjoyjava@gmail.com>
    stack.appsody.dev/configured: docker.io/kabanero/nodejs-loopback:0.1
    stack.appsody.dev/created: "2020-01-28T12:00:38Z"
    stack.appsody.dev/description: LoopBack 4 API Framework for Node.js
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/kabanero/nodejs-loopback:0.1.8
    stack.appsody.dev/title: LoopBack 4
    summary: Image for Kabanero Node.js Loopback development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/nodejs-10/images/1-54
    usage: s2i build <SOURCE-REPOSITORY> ubi8/nodejs-10:latest <APP-NAME>
    vcs-ref: 6ee7553ab2fb0dc20817416392fa6025cd1003c7
    vcs-type: git
    vendor: Kabanero
    version: 0.1.4
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-nodejs-loopback
    stack.appsody.dev/id: nodejs-loopback
    stack.appsody.dev/version: 0.1.8
  name: sample-nodejs-loopback
spec:
  applicationImage: dev.local/sample-nodejs-loopback
  createKnativeService: true
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    port: 3000
    type: NodePort
  stack: nodejs-loopback
  version: 1.0.0
status: {}
