apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2020-02-06T14:02:17-05:00"
    stack.appsody.dev/authors: Raymond Feng <enjoyjava@gmail.com>
    stack.appsody.dev/configured: docker.io/appsody/nodejs-loopback:0.2
    stack.appsody.dev/created: "2020-01-20T15:44:51Z"
    stack.appsody.dev/description: LoopBack 4 API Framework for Node.js
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/nodejs-loopback:0.2.1
    stack.appsody.dev/title: LoopBack 4
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-nodejs-loopback
    stack.appsody.dev/id: nodejs-loopback
    stack.appsody.dev/version: 0.2.1
  name: sample-nodejs-loopback
spec:
  applicationImage: dev.local/sample-nodejs-loopback
  createKnativeService: true
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    port: 3000
    type: NodePort
  stack: nodejs-loopback
  version: 1.0.0
status: {}
